### PR TITLE
Do not leak Azure credentials

### PR DESCRIPTION
**Pull request by schiermi**

### CODE REVIEW

**Comment by schiermi** [comment]
Just spotted other leaks. How to talk to Azure without sending app credentials to auth.pritunl.com?

**Comment by pascal-hofmann** [comment]
Wow, that's crazy. I guess one should take "No Hidden Backdoors" as written on https://pritunl.com/security literally. There are no hidden backdoors. They are public.

**Comment by zachhuff386** [comment]
All single sign-on is handled by the Pritunl authentication servers. This protects paid enterprise functionality and allows quickly patching sensitive authentication code. Had the SAML XML authentication bypass impacted Pritunl it could have been quickly patched, although the Golang XML library used on the authentication servers was not impacted.

These keys have very limited scope with minimal to no impact on security of the Azure account. To the extent that it is backdoor, Microsoft would also have a backdoor. Both Pritunl and the single sign-on provider must be trusted. If this is a concern multi-factor authentication can be configured with Duo and all authentication would be handled by two separate providers. Duo authentication is not processed by the Pritunl authentication servers.

**Comment by pascal-hofmann** [comment]
Still this is an issue for all European customers, because they simply are not allowed to let personal data be processed in the US, where your authentication server is hosted. I think this should be stated prominently somewhere in the docs.

**Comment by Dmkaz** [comment]
This is the primary reason that our organization chose to discontinue our Pritunl enterprise subscription. 

Enterprise users also do **not** have the option to locally host this authentication server. 

Much like @zachhuff386 said above, this is seemingly only to protect the 'paid enterprise functionality', which I fully understand. However, because of this obfuscation the trust model is broken with Pritunl as: 
- There is no explicit mention of this 'auth server' in the documentation with relation to the SSO trust-chain.
- There exists no option to locally host this auth server for enterprise users.

Our organization would happy renew our paid subscription should this be made available as an option. 

As it stands, due to legal restrictions, such as GDPR and others, we cannot allow this link in our trust chain or environment.

**Pull request closed without merging**
