### PR TITLE
Migrate Pritunl Azure SSO to Microsoft Graph API

### PR DESCRIPTION
**Pull request by sgrzemski**
Hello Pritunl developers,

Azure AD Graph API is deprecated. Pritunl has to be switched to use Microsoft Graph API. 
Previously, Pritunl required Directory.Read.All API permission, which was excessive and potentially vulnerable. It might be also a problem when working with big AD sets. I have introduced the new API url, fixed all request params and changed the logic of getting user groups to match new Microsoft Graph API.

Thank you in advance,
Szymon

### CODE REVIEW

**Comment by zachhuff386** [comment]
This wouldn't be compatible with existing configurations. All users currently have only the Azure Active Directory Graph API permissions configured. This change would break all existing configurations. A migration to the new API will be added in a future release.

**Comment by TheBigBear** [comment]
@zachhuff386 can you show where this was added instead, so it does indeed get actioned ASAP? we really need this, this is NOT really an "optional" improvement, this is a MUST do.
 
@sgrzemski Szymon is the SSO provider in pritunl FREE, or is this functionality dependant on having some sort of ongoing subscription with or for pritunl ?

**Comment by eimann** [comment]
Apparently the Enterprise subscription still doesn't support Microsoft Graph API.
The Pritunl docs are outdated and refer to the old AAD Graph API.
Support requests aren't answered.

**Comment by zachhuff386** [comment]
Microsoft gave dates in 2022 for removing this API. If Microsoft has unexpectedly disabled something in Azure then contact Microsoft. Simply changing the URL as this pull request has done will not fix the issue. Doing that would break all VPN connections for every user that upgrades Pritunl without first updating their Azure configuration. An update for Pritunl will be made available in the future to handle the transition to the new API.

**Comment by zachhuff386** [comment]
An update for the new Azure API will be available in the [**unstable repository**](https://docs.pritunl.com/docs/repo#unstable-repositories) in a few hours. The command `sudo pritunl set app.sso_azure_version 2` will enable the new API.

**Comment by eimann** [comment]
Thanks Zach. Using the unstable repo and enabling the new API worked like a charm.

**Comment by Akashdeep-Munjal** [comment]
> An update for the new Azure API will be available in the [**unstable repository**](https://docs.pritunl.com/docs/repo#unstable-repositories) in a few hours. The command `sudo pritunl set app.sso_azure_version 2` will enable the new API.

@zachhuff386 I updated to sudo pritunl set app.sso_azure_version 2, but still getting same error with MS Graph API.

**Comment by Akashdeep-Munjal** [comment]
It worked.

**Comment by samalazau** [comment]
For everyone who struggles the same issue on AWS Linux:

`wget https://repo.pritunl.com/unstable/yum/amazonlinux/2/pritunl-1.30.2969.92-1.amzn2.x86_64.rpm && yum localinstall pritunl-*.rpm && sudo pritunl set app.sso_azure_version 2`

**Pull request closed without merging**
